Traceback (most recent call last):
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/haoting/.pyenv/versions/3.7.14/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cc = pd.read_csv(path_root / 'ds000030' / fmriprep_version /'dataset-ds000030_atlas-mist_nroi-444_connectome.tsv', sep='\t', index_col=0)

for strategy in cc.columns:
    mat = vec_to_sym_matrix(cc[strategy], np.zeros(444))
    g = plot_matrix(mat, labels=None, reorder='complete', title=strategy, vmax=1, vmin=-1)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_23143/1919540662.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfor[0m [0mstrategy[0m [0;32min[0m [0mcc[0m[0;34m.[0m[0mcolumns[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mmat[0m [0;34m=[0m [0mvec_to_sym_matrix[0m[0;34m([0m[0mcc[0m[0;34m[[0m[0mstrategy[0m[0;34m][0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;36m444[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m     [0mg[0m [0;34m=[0m [0mplot_matrix[0m[0;34m([0m[0mmat[0m[0;34m,[0m [0mlabels[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0mreorder[0m[0;34m=[0m[0;34m'complete'[0m[0;34m,[0m [0mtitle[0m[0;34m=[0m[0mstrategy[0m[0;34m,[0m [0mvmax[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mvmin[0m[0;34m=[0m[0;34m-[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0mplt[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nilearn/plotting/matrix_plotting.py[0m in [0;36mplot_matrix[0;34m(mat, title, labels, figure, axes, colorbar, cmap, tri, auto_fit, grid, reorder, **kwargs)[0m
[1;32m    267[0m     )
[1;32m    268[0m     [0;32mif[0m [0mreorder[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 269[0;31m         [0mmat[0m[0;34m,[0m [0mlabels[0m [0;34m=[0m [0m_reorder_matrix[0m[0;34m([0m[0mmat[0m[0;34m,[0m [0mlabels[0m[0;34m,[0m [0mreorder[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    270[0m     [0;32mif[0m [0mtri[0m [0;34m!=[0m [0;34m"full"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    271[0m         [0mmat[0m [0;34m=[0m [0m_mask_matrix[0m[0;34m([0m[0mmat[0m[0;34m,[0m [0mtri[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.7/site-packages/nilearn/plotting/matrix_plotting.py[0m in [0;36m_reorder_matrix[0;34m(mat, labels, reorder)[0m
[1;32m    110[0m     """
[1;32m    111[0m     [0;32mif[0m [0;32mnot[0m [0mlabels[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 112[0;31m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Labels are needed to show the reordering."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    113[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    114[0m         from scipy.cluster.hierarchy import (linkage,

[0;31mValueError[0m: Labels are needed to show the reordering.
ValueError: Labels are needed to show the reordering.

